export type Lang = "ru" | "en";

export const translations = {
  ru: {
    nav: { about: "Обо мне", services: "Услуги", projects: "Проекты", contact: "Контакты" },
    hero: {
      title: "developer",
      subtitle: "vibe coder",
      lead: "начинающий, но быстро растущий разработчик, создающий продукты на стыке кода и нейросетей",
      contact: "Написать мне",
    },
    about: {
      heading: "Обо мне",
      text: "Я junior-разработчик, который делает ставку на скорость и AI-инструменты: собираю веб-приложения, автоматизации и LLM-интеграции от идеи до продакшена. Люблю разбирать сложные задачи на понятные шаги и доводить проекты до реального результата. Дальше — больше.",
      contact: "Написать мне",
    },
    services: {
      heading: "Услуги",
      items: [
        {
          num: "01",
          name: "Веб-приложения и сайты",
          desc: "Разработка сайтов и веб-приложений — от лендингов до полноценных сервисов с бэкендом и базой данных.",
        },
        {
          num: "02",
          name: "Автоматизация и боты",
          desc: "Скрипты, боты и автоматизация рутинных задач — экономия времени и снижение количества ручной работы.",
        },
        {
          num: "03",
          name: "LLM-интеграции",
          desc: "Встраивание языковых моделей в продукты: умные подсказки, генерация контента, AI-ассистенты и агенты.",
        },
      ],
    },
    projects: {
      heading: "Проекты",
      live: "Открыть проект",
      soon: "Скоро",
      items: [
        {
          num: "01",
          category: "Личный проект",
          name: "Valocoach",
          tag: "AI-интеграция",
          description:
            "AI-коуч по Valorant: статистика по реальным матчам, сравнение со средним игроком ранга и план тренировок на неделю, который генерирует LLM.",
        },
      ],
    },
    marquee: {},
  },
  en: {
    nav: { about: "About", services: "Services", projects: "Projects", contact: "Contact" },
    hero: {
      title: "developer",
      subtitle: "vibe coder",
      lead: "a junior but fast-growing developer building products at the intersection of code and AI",
      contact: "Contact Me",
    },
    about: {
      heading: "About me",
      text: "I'm a junior developer betting on speed and AI-assisted tooling: I build web apps, automations, and LLM integrations from idea to production. I enjoy breaking hard problems into clear steps and shipping real, working results. More is coming.",
      contact: "Contact Me",
    },
    services: {
      heading: "Services",
      items: [
        {
          num: "01",
          name: "Web apps & websites",
          desc: "Building websites and web applications — from landing pages to full-stack services with a backend and database.",
        },
        {
          num: "02",
          name: "Automation & bots",
          desc: "Scripts, bots, and automation for repetitive tasks — saving time and cutting manual work.",
        },
        {
          num: "03",
          name: "LLM integrations",
          desc: "Embedding language models into products: smart suggestions, content generation, AI assistants and agents.",
        },
      ],
    },
    projects: {
      heading: "Projects",
      live: "Live Project",
      soon: "Coming soon",
      items: [
        {
          num: "01",
          category: "Personal project",
          name: "Valocoach",
          tag: "AI integration",
          description:
            "An AI Valorant coach: real match stats, radar comparison against the rank average, and a weekly training plan generated by an LLM.",
        },
      ],
    },
    marquee: {},
  },
};
